version: "2"

services:
  application:
    image: nginx
    volumes:
      - .:/application
   #   - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "9000:9000"
    networks:
      - backend

  php:
    build: .
    volumes:
      - .:/application    
    networks:
      - backend

  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=yalla
      - MYSQL_ROOT_PASSWORD=yolémek
      - MYSQL_USER=yallamasselot
      - MYSQL_PASSWORD=yolémektonz
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend

volumes:
  data:

networks:
  backend:
